[project]
name = "arxivscraper"
version = "0.0.5"
authors = [
    { name = "mahdisadjadi", email = "sadjadi.seyedmahdi@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pip>=25.1.1",
    "pytest>=8.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
